### ISSUE TITLE
Science track

### ISSUE THREAD

**Issue by snim2** [PyconUK/voting#13]
Should the talk titles file include sessions from the Science track, or are we leaving these out because they are already scheduled?

**Comment by inglesp** [comment]
As I understood it, the purpose of this app is to help with scheduling, so that we can put the most popular talks in the biggest rooms.  Since the Science track talks are already scheduled, we don't need to include them.

@snim2 -- happy with that?

**Comment by snim2** [comment]
Sounds perfectly sensible to me. I would close this issue now, if my mobile GH app had a button for it!

**Comment by snim2** [comment]
Turns out there is such a button!
