### ISSUE TITLE
Reviewed proposals page omits info

### ISSUE THREAD

**Issue by snim2** [PyconUK/voting#16]
On the top right of this screenshot you can see some text which says **proposals remaining of** and the numbers at the start and end of that sentence are missing.

![reviewed-cropped](https://cloud.githubusercontent.com/assets/97674/8802508/f4a23c98-2fb9-11e5-813b-a4bae43450ac.png)

**Comment by snim2** [comment]
The "unreviewed proposals" page seems fine though...

**Comment by ghickman** [comment]
Fixed in #19, thanks @snim2
