### ISSUE TITLE
There's no way to log out of the voting app - ie delete the cookie

### ISSUE THREAD

**Issue by jonathanfine** [PyconUK/voting#22]
As subject (other than through developer tools).

**Comment by jonathanfine** [comment]
I've just deleted my cookies (on firefox) and now when I visit the app I get Server Error (500).  Perhaps this should be a separate issue.

**Comment by jonathanfine** [comment]
I've deleted the cookie (using browser tools) and now the app gives Server Error (500).  Perhaps this should be a separate issue.

**Comment by jonathanfine** [comment]
Oops - I've closed it by mistake.

**Comment by ghickman** [comment]
@jonathanfine – this is correct, there is no need for a user to log out so I haven't set that up.

Thanks for catching the 500, I got an opbeat notification and fixed last night =)
