### ISSUE TITLE
Branding looks funny in mobile / portrait

### ISSUE THREAD

**Issue by snim2** [PyconUK/voting#24]
See screenshot here:

https://www.dropbox.com/s/o2mpnw6avj78848/Screenshot_2015-07-22-19-39-11.png?dl=0

**Comment by snim2** [comment]
Landscape looks fine!

**Comment by inglesp** [comment]
This is improved by #25.  Tested on iOS and (ahem) Firefox OS.

@snim2, please close if you're happy this is good enough to launch.

**Comment by snim2** [comment]
Looks OK to me!
