### ISSUE TITLE
Random order not seeded and may be expensive

### ISSUE THREAD

**Issue by jonathanfine** [PyconUK/voting#27]
The views.py line

``` python
return redirect('proposal-detail', pk=proposals.order_by('?').first().pk)
```

gives the random order.  A better way might be to generate a random order up front for each new user, and store it in the database.  A change would also have to be made to ordering = '?' in UnreviewedProposals.

According to https://docs.djangoproject.com/en/1.8/ref/models/querysets/#order-by this ' may be expensive and slow, depending on the database backend you’re using'.

**Comment by jonathanfine** [comment]
This is nice to have.  But I don't think it should block release.

**Comment by inglesp** [comment]
I'm closing this until we've got evidence that this is actually a problem.

**Comment by jonathanfine** [comment]
As it happens, there is a problem.  Look at http://pyconuk-voting.herokuapp.com/unreviewed/.  The proposals are in a random order.  Now refresh the page.  They are in a _different_ random order.  The will confuse the user, if only at an unconscious level.  (I half noticed this before looking at the code, and dismissed it from my mind.)

Please leave this issue open, so it is not forgotten.  Closed issues are forgotten.  I don't regard it as blocking release - maybe attach it to another milestone.

**Comment by ntoll** [comment]
@jonathanfine what evidence (other than your own opinion) do you have that this is a problem. Personally, I don't see a problem at all.

**Comment by jonathanfine** [comment]
Perhaps we don't need to store a random permutation per user.  We can generate it (the same each time) every time we need it, from the user's login id.  This can be done using random.seed() and random.shuffle().  However, there may be problems with being thread-safe - this would need to be checked.

I don't have time now to write a patch.

**Comment by jonathanfine** [comment]
@ntoll what evidence could I have at this time other than my own experience and knowledge?  Thank you for sharing your opinion.

**Comment by ntoll** [comment]
@jonathanfine therein lies the problem. ;-)

I'd be totally 100% behind you if our users where complaining about this. Let's see what they say!

**Comment by ghickman** [comment]
I see three points here:
- building a random ordering for users up front
- `order_by('?')` being expensive
- unreviewed talks reordering on each page load

### Upfront generation

I'm don't see what we'd gain here other than increased code complexity. Django offers a DB level random ordering function that works (and _is_ both working and performant in production).

### Order_by's expense

As mentioned in #15, I do not believe this to be an issue. I've made use of this function on sites with far larger datasets than this one (theoretical max of ~12K votes (194 users \* 66 talks)). This is not a lot of data, especially for a database like Postgres. Having looked at the Heroku logs the longest response time I could see is 234ms for the reviewed talks page, talk detail pages are taking ~55ms to load. These numbers are very good, we do not need to fix this.

### Unreviewed talks reordering

I consider this a feature, albeit unintentionally so. We redirect users to the next random talk after a vote & from the homepage to try and avoid bias, the unreviewed talks page mirrors this functionality. Should we order by any other reasonable field (name, etc) then we would introduce a bias.

---

Until we have concrete metrics on `order_by('?')` being a performance issue, and to avoid premature optimisation, I'm going to close this issue.
