### ISSUE TITLE
Allow users to log in with Twitter, Facebook, Google, GitHub accounts

### ISSUE THREAD

**Issue by ntoll** [PyconUK/voting#3]
Really sorry 'bout this. There must be a plug-in that makes this possible..?

OAuth - guaranteed to leave a bad taste in your mouth. Feel free to tell me to go to hell with this... ;-)

**Comment by Lukasa** [comment]
I believe this is the thing you're looking for: [python-social-auth](https://github.com/omab/python-social-auth).

**Comment by ghickman** [comment]
Yep, there's a few of these IIRC. As long as they plug into a Custom User Model any of them are fine.

I'd suggest a list of buttons below or to the right of the login/register form.

**Comment by meshy** [comment]
If I log in with my gmail, twitter, and facebook, does that mean I get three votes?

**Comment by meshy** [comment]
Is there a way of tying it to tickets instead?

**Comment by ghickman** [comment]
I _think_ you can tie multiple social accounts to one user… if I'm reading the docs correctly.

It looks like it'll be easier to drop the Custom User Model and let python-social-auth deal with email registration too.

**Comment by ghickman** [comment]
Current work is up on the `social-auth` branch.

**Comment by ghickman** [comment]
Closing based on my email to the list (happy to reopen later if we decide it's appropriate).
